from django.urls import path, include
from main.views import *
from main.views import show_main, register, login_user, logout_user, show_json, show_json_by_id, search_by_title, show_book_entry, create_custom_entry, create_catalog_entry, BookListAPIView, get_entry_by_id, edit_entry, show_book_entry_other, create_book_post
from main.views import get_books_by_id, delete_entry, get_books, get_books_by_tag, show_users, delete_user, copy_entry, get_posts_json, reject_tag, create_post, accept_tag, make_admin, revoke_admin, get_books_by_type, make_favourite, accept_book, reject_book, get_book_posts_json, get_bookposts_json, Book_EntryList
from main.views import Bookpost_List, Tagpost_List, create_bookpost_flutter, accept_book_flutter, reject_book_flutter, create_tagpost_flutter
from main.views import fetch_tags, create_custom_flutter, create_catalog_flutter, Other_Users,  edit_entry_flutter, delete_entry_flutter, CurrentUser
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('search_title', search_by_title, name='search-title'),
    path('entry/', show_book_entry , name='show_entry'),
    path('create-custom-entry/', create_custom_entry, name = 'create_custom_entry' ),
    path('create-catalog-entry/', create_catalog_entry, name = "create_catalog_entry"),
    path('BookAPIView/', BookListAPIView.as_view(), name = "BookAPIView"),
    path('get-books-by-id/<int:id>', get_books_by_id, name='get_books_by_id'),
    path('get-books/', get_books, name='get_books'),
    path('get-books/<str:tag>', get_books_by_tag, name='get_books_by_tag'),
    path('get-books-type/<str:type>', get_books_by_type, name='get_books_by_type'),
    path('get-entry-by-id/<int:id>', get_entry_by_id, name = "get_entry_by_id"),
    path('edit-entry/<int:id>', edit_entry, name = "edit_entry"),
    path('entry/<str:username>', show_book_entry_other , name='show_entry_other'),
    path('delete-entry/<int:id>', delete_entry, name = "delete_entry"),
    path('show-other-users/', show_users, name="show_other_users"),
    path('delete-user/<str:username>', delete_user, name='delete_user'),
    path('make-admin/<str:username>', make_admin, name='make_admin'),
    path('revoke-admin/<str:username>', revoke_admin, name='revoke_admin'),
    path('create-post/', create_post, name='create_post'),
    path('copy-entry/', copy_entry, name='copy_entry'),
    path('get-posts/', get_posts_json, name='get_posts_json'),
    path('reject-tag/<int:id>', reject_tag, name='reject_tag'),
    path('accept-tag/<int:id>', accept_tag, name='accept_tag'),
    path('make-favourite/<int:id>', make_favourite, name='make_favourite'),
    path('create-book-post/', create_book_post, name='create_book_post'),
    path('accept-book/<int:id>', accept_book, name='accept_book' ),
    path('reject-book/<int:id>', reject_book, name='reject_book' ),
    path('get-book-post/<int:id>', get_book_posts_json, name='get_book_posts_json'),
    path('get-bookpost/', get_bookposts_json, name='get_bookposts_json'),
    path('Galih/', Book_EntryList.as_view(), name='book-entry-list'),
    path('fetch-tags/', fetch_tags, name = 'fetch_tags'),
    path('create-custom-flutter/', create_custom_flutter, name = 'create_custom_flutter'),
    path('create-catalog-flutter/', create_catalog_flutter, name = 'create_catalog_flutter'),
    path('edit-entry-flutter/', edit_entry_flutter, name = 'edit_entry_flutter'),
    path('delete-entry-flutter/', delete_entry_flutter, name = 'delete_entry_flutter'),
    path('flutter-catalog/', BookListAPIView.as_view(), name='book-catalog'),
    path('other-users/', Other_Users.as_view(), name='other-users'),
    path('entry_flutter/<str:username>/', Book_EntryList_Flutter.as_view() , name='show_entry_other_flutter'),
    path('make_admin_flutter/<str:username>/', make_admin_flutter, name='make-admin-flutter'),
    path('revoke_admin_flutter/<str:username>/', revoke_admin_flutter, name='revoke-admin-flutter'),
    path('delete_user_flutter/<str:username>/', delete_user_flutter, name='delete-user-admin'),
    path('current-user/', CurrentUser.as_view(), name='current-user'),
    path('bookpost-list/', Bookpost_List.as_view(), name='bookpost-list'),
    path('tagpost-list/', Tagpost_List.as_view(), name='tagpost-list'),
    path('create-bookpost-flutter/', create_bookpost_flutter, name = 'create_bookpost_flutter'),
    path('accept-book-flutter/<int:id>/', accept_book_flutter, name='accept_book_flutter' ),
    path('reject-book-flutter/<int:id>/', reject_book_flutter, name='reject_book_flutter' ),
    path('accept-tag-flutter/<int:id>/', accept_tag_flutter, name='accept_tag_flutter'),
    path('reject-tag-flutter/<int:id>/', reject_tag_flutter, name='reject_tag_flutter'),
    path('create-tagpost-flutter/', create_tagpost_flutter, name='create_tagpost_flutter'),
]
