# Generated by Django 4.2.6 on 2023-10-22 05:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Novel', 'Novel'), ('Manhwa', 'Manhwa'), ('Manga', 'Manga'), ('LN', 'Light Novel')], default='Manga', max_length=15)),
                ('author', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('D', 'Dropped'), ('R', 'Reading'), ('P', 'Plan to read'), ('O', 'On Hold'), ('F', 'Finished')], default='P', max_length=2)),
                ('last_chapter_read', models.IntegerField()),
                ('last_read_date', models.DateField()),
                ('review', models.TextField()),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_Entry',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.book_entry')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Novel', 'Novel'), ('Manhwa', 'Manhwa'), ('Manga', 'Manga'), ('LN', 'Light Novel')], default='Manga', max_length=15)),
                ('author', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Catalog_Entry',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.book_entry')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
            ],
        ),
    ]
