# Generated by Django 4.2.6 on 2023-10-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Novel', 'Novel'), ('LN', 'Light Novel'), ('Manga', 'Manga'), ('Manhwa', 'Manhwa')], default='Manga', max_length=15),
        ),
        migrations.AlterField(
            model_name='book_entry',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('D', 'Dropped'), ('P', 'Plan to read'), ('R', 'Reading'), ('O', 'On Hold')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='custom_entry',
            name='type',
            field=models.CharField(choices=[('Novel', 'Novel'), ('LN', 'Light Novel'), ('Manga', 'Manga'), ('Manhwa', 'Manhwa')], default='Manga', max_length=15),
        ),
    ]
