# Generated by Django 4.2.6 on 2023-10-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_type_alter_book_entry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Novel', 'Novel'), ('LN', 'Light Novel'), ('Manhwa', 'Manhwa'), ('Manga', 'Manga')], default='Manga', max_length=15),
        ),
        migrations.AlterField(
            model_name='book_entry',
            name='status',
            field=models.CharField(choices=[('R', 'Reading'), ('F', 'Finished'), ('D', 'Dropped'), ('O', 'On Hold'), ('P', 'Plan to read')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='custom_entry',
            name='type',
            field=models.CharField(choices=[('Novel', 'Novel'), ('LN', 'Light Novel'), ('Manhwa', 'Manhwa'), ('Manga', 'Manga')], default='Manga', max_length=15),
        ),
    ]
