# Generated by Django 4.2.6 on 2023-10-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_book_type_alter_book_entry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Manga', 'Manga'), ('Manhwa', 'Manhwa'), ('LN', 'Light Novel'), ('Novel', 'Novel')], default='Manga', max_length=15),
        ),
        migrations.AlterField(
            model_name='book_entry',
            name='status',
            field=models.CharField(choices=[('P', 'Plan to read'), ('R', 'Reading'), ('F', 'Finished'), ('O', 'On Hold'), ('D', 'Dropped')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='custom_entry',
            name='type',
            field=models.CharField(choices=[('Manga', 'Manga'), ('Manhwa', 'Manhwa'), ('LN', 'Light Novel'), ('Novel', 'Novel')], default='Manga', max_length=15),
        ),
    ]
