# Generated by Django 4.2.6 on 2023-10-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_book_imagelink_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_entry',
            name='imagelink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='custom_entry',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='custom_entry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
