# Generated by Django 4.2.5 on 2023-10-26 15:25

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "books.json")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_book_tags_book_tags'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
