# Generated by Django 4.2.6 on 2023-10-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_tags_book_taglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='taglist',
            new_name='tags',
        ),
    ]
