# Generated by Django 4.2.6 on 2023-10-28 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_inserting_data_with_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Manga', 'Manga'), ('Manhwa', 'Manhwa'), ('Light Novel', 'Light Novel'), ('Novel', 'Novel')], default='Manga', max_length=15),
        ),
        migrations.AlterField(
            model_name='book_entry',
            name='last_chapter_read',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_entry',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='book_entry',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custom_entry',
            name='type',
            field=models.CharField(choices=[('Manga', 'Manga'), ('Manhwa', 'Manhwa'), ('Light Novel', 'Light Novel'), ('Novel', 'Novel')], default='Manga', max_length=15),
        ),
    ]
