# Generated by Django 4.2.6 on 2023-10-28 04:39

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('main', '0015_alter_book_type_alter_book_entry_last_chapter_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_entry',
            name='taggits',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
